### ISSUE TITLE
Update demo?

### ISSUE THREAD

**Issue by solodev** [FortesSolutions/backgrid-sizeable-columns#5]
I am not sure what I am missing, but when I use the demo code it works:

http://techwuppet.com/backgrid_poc_demo/

But, when I use your latest updates it does not work.  It seems like the latest update has numerous changes.  Any advise?

**Comment by WRidder** [comment]
@solodev Thanks for the heads up, we'll look into it!

**Comment by WRidder** [comment]
Demo is in the works, see: https://github.com/WRidder/backgrid-demo

**Comment by excentris** [comment]
@WRidder can you let me know when the new demo site is fully working so I can close this issue? Thanks in advance!

**Comment by WRidder** [comment]
Sure! Still refactoring the orderable columns plugin. Will update once ready.

**Comment by excentris** [comment]
@solodev new demo site is up and running. Closing this issue.
